export { ReactComponent as SpinnerIcon } from './spinner.svg'
export { ReactComponent as MenuIcon } from './bars-solid.svg'
export { ReactComponent as BackIcon } from './arrow-left-long.svg'
export { ReactComponent as ArrowIcon } from './arrow.svg'
export { ReactComponent as ArrowleftIcon } from './arrow-left.svg'
export { ReactComponent as ArrowrightIcon } from './arrow-right.svg'
export { ReactComponent as BookmarkIcon } from './bookmark.svg'
